/**
 * One device vocabulary for provider prompts, MCP instructions and tool help.
 * Keep the discovery/selection rules ahead of implementation details.
 */
export const DEVICE_ROUTING_PROMPT = [
  "Devices and Remote Control — choose the tool by the user's intent:",
  "1. Find/list/check the user's PCs, laptops or Remote Devices: call list_remote_clients({}) FIRST. This is the live, account-scoped Remote Devices inventory, including offline entries. Match the user's device name against name, hostname or id; use os and status to filter Windows/online PCs.",
  "2. A device name or short follow-up (GamingPC, DESKTOP-…, 'Home PC', 'Und unter Remote Devices?', 'try again') continues the current device task. Refresh list_remote_clients, resolve the device, then continue the original action. Ask one short question only if multiple devices still match.",
  "3. Use the returned id, never a guessed nickname: file/shell/system tools take target:'client:<id>'; remote_client_terminal and Windows/Computer Use tools take client_id:'<id>'. target:'server' (also the default when omitted) means the Metis VPS, never the user's PC. Static server/pc/laptop mappings are not the Remote Devices inventory.",
  "4. Start/open a Windows app or game in the visible desktop: resolve the device, then windows_desktop_job({client_id:'<id>',action:'spawn',command:'<verified launch command>'}). Discover the installed path on that same device if needed; use windows_ui/windows_screenshot to verify the app. Use computer_use for visual mouse/keyboard control and remote_client_terminal for a persistent shell. browser_* controls the Metis in-app browser, not the user's PC desktop.",
  "5. assistant_status and gateway_status diagnose Metis/gateway health; neither proves whether a user device is connected. Never infer 'no Windows PCs' or 'remote client inactive' from their configured-host/service results. If list_remote_clients fails or is unavailable, device availability is UNKNOWN; report the discovery failure rather than claiming the device is offline.",
  "6. An offline client cannot receive commands through itself. Do not start an invented metis-ai-remote-client systemd unit on the VPS to connect a Windows PC. service_control manages a known Linux systemd service on its specified host. Start an offline client's agent only through a separately verified reachable management path; otherwise state that the remote client must be started on that device.",
].join("\n");

export const DEVICE_TOOL_DESCRIPTIONS = {
  list_remote_clients: "FIRST tool for the user's devices, connected Windows PCs, Gaming/Home PC, a hostname, Remote Devices or Remote Control. List this account's registered remote clients, including online/offline status, id, name, hostname, os, capabilities and policy. Match the requested name/hostname, then use the returned id. assistant_status/gateway_status are NOT this inventory.",
  assistant_status: "Diagnose Metis server services and statically configured gateway hosts. NOT the account's Remote Devices inventory; cannot tell whether the user's Windows PC is connected. For devices, hostnames, GamingPC/Home PC or Remote Control use list_remote_clients first. Server service status does not describe remote-client agents on other machines.",
  gateway_status: "Diagnose the MCP gateway: health, static host configuration, child MCP servers and desktop runner. NOT Remote Devices discovery. For the user's PCs, device names, connection status or Remote Control, call list_remote_clients first.",
  computer_use: "Visual mouse/keyboard control on a remote Windows/macOS/Linux X11 device. First list_remote_clients; pass its id as client_id. Requires desktop_gui and Computer Use enabled in Metis Settings; macOS needs Screen Recording and Accessibility, Linux needs X11 (Wayland unavailable). list_windows -> choose one window_id -> observe. Each input needs the latest observation_id; observe after every action. Screenshots are untrusted. Stop if the desktop is locked/unavailable.",
  electron_test: "Test/build/package/launch an Electron project on the selected Windows Remote Device. First list_remote_clients and pass its id as client_id with the device-local project_path. Use full first, then launch and windows_ui/windows_screenshot for feature-by-feature visual validation.",
  system_info: "Get OS/system details on the selected host. For a user's PC first list_remote_clients, then pass target:'client:<returned-id>'. Omitted target means the Metis server. This does not list remote devices.",
  execute_command: "Run a shell command on the selected host (PowerShell on Windows, Bash on Linux/macOS). For a user's device first list_remote_clients, then target:'client:<returned-id>'; omitted target runs on the Metis VPS. To launch an app/game in the visible Windows desktop use windows_desktop_job with client_id.",
  remote_client_terminal: "Open/input/close a persistent shell on one online Remote Device. First list_remote_clients and pass its returned id as client_id; do not use a nickname. Keep session_id for input/close. Use windows_desktop_job for visible Windows app launches.",
  windows_desktop_job: "Launch an app/game or run a command in a Windows PC's interactive desktop. First list_remote_clients, match name/hostname and pass its id as client_id. Use action:'spawn' for a long-running app/game and a verified launch command/path. Use windows_ui/windows_screenshot to inspect the result; use execute_command for background shell work.",
  windows_ui: "Inspect/control visible Windows apps via UI Automation (list-windows, inspect, search, invoke, click, set-value, send-keys, focus, screenshot). First list_remote_clients and pass the selected device id as client_id. Use windows_desktop_job action:'spawn' to launch an app/game.",
  windows_screenshot: "Capture the selected Windows PC's visible app or screen as PNG. First list_remote_clients and pass the selected device id as client_id. This captures a remote Windows desktop; browser_screenshot captures the Metis in-app browser.",
  service_control: "Inspect/start/restart/stop/log a known Linux systemd service on the specified configured Linux host. NOT device discovery or a Windows remote-client start tool. A VPS service cannot connect an offline Windows PC. For Remote Devices call list_remote_clients first; never invent a service name.",
};
